---
title: "ADCN: Demand and Capacity, College Sports, Youth Burnout ... and More News"
author: "Brad Stenger"
date: "2025-12-31"
---

Work on developing this newsletter continues. I'm pushing in the direction of something quicker and newsier for 2026. Thanks for reading!

### Demand and Capacity

Structural engineers use Demand-Capacity models to understand risk related to buildings and bridges. Capacity refers to the unit's strength based on its design and material construction. The external forces that the unit experiences is the Demand. When Capacity is greater than Demand we are safe. Athletes' Injury Risk models based on Training Load data fail to parse Capacity and Demand, neglecting some really useful descriptive details in the process.

Let's look first at Capacity. Capacity closely approximates Training Load as an indicator of athletes' fitness. A more complete story for Capacity should also include Readiness parameters that come from recovery, stress and sleep biometrics. To go on with the building analogy, Capacity is the design, construction and ongoing maintenance for athletes. Training, injury and return-to-play from injury are Capacity supplements and reductions.

Examples: Greek researchers [showed](https://onlinelibrary.wiley.com/doi/10.1111/sms.70169?af=R) that even short flights (< 5 hours) deteriorate athletic performance, probably because of lost sleep. Athlete performance consultant Peter Tierney [recently posted](https://x.com/drpetertierney/status/2003477308745875899) the benefit of sprint training for athletes, with greater benefit to athletes with high training loads. Whoop posted Christiano Ronaldo's [year-end data summary](https://x.com/WHOOP/status/2004602034226700795) from the company's wearable sensing platform.

Demand refers to all of the external forces that apply in the context of athletic competition. Some of these forces are controllable. Some are not. Changes to a game model or game plan can ask more or ask less of specific players. Weather and play surface can be controlled indoors but are subject to unpredictable factors (temperature, traction) outdoors. A team's or an athlete's personal goals for individual performance, recognition or achievement can also apply a psychosocial demand.

Examples: The *British Journal of Sports Medicine* published [a study](https://bjsm.bmj.com/content/bjsports/59/23/1643.full.pdf) led by Tom Allen from Arsenal that calculated changes in running load and fixture congestion for Premier League players since the 2015-16 season. Allen and co-authors cite, "Running load demands (TD, HID, HSR, SprD, HID/min, HSR/min and SprD/min), total match minutes and congested minutes have increased over the last decade." Professional soccer athletes James Milner and Steph Houghton also collaborated on [an essay](https://bjsm.bmj.com/content/59/23/1703?rss=1) for BJSM that documents their experience with more running and more games compared to earlier in their careers.

Demand-Capacity models are, in many cases, instantiated by formulating the Demand-Capacity ratio (DCR). When Demand/Capacity (Demand divided by Capacity) is greater than 1 then it equates to failure in structural engineering situations. Given the relatively rare instances of athletes' injury, it would be difficult for DCR to predict injury right off the bat so "Injury = Failure" may not be the proper context for an Athletes DCR. A more realistic starting point is to use changes in DCR to describe an athlete's performance decline in terms of expected or actual values, whether from age or injury or both. 

It also makes sense to sum the Demand and the Capacity for all of the individual players on a team in order to generate a team-wide DCR. Injury cascades (and other major Capacity changes) and fixture congestion results (and other major Demand changes) would surface with real clarity. 

Teams should also be able to observe positive and negative effects from collaboration and teamwork as teams that work together for easier scores would show lower Demand and lower DCR for the same results. [Reports about the recent success](https://x.com/BrendanRMarks/status/2003453206551241104) of Vanderbilt mens basketball, and its emphasis on unselfish playing style, show the substantial benefit from high levels of players' cohesion in team sports. At least that is the hypothesis, that better teamwork can reduce individual athletes' wear and tear.


### College Sports, Sport by Sport Changes

I went to Northwestern with ESPN's college sports writer Dan Murphy who [profiled](https://www.espn.com/college-football/story/_/id/47412557/cody-campbell-booster-texas-tech-college-sports) Cody Campbell, describing Campbell's role in evolving the business models so that U.S. college sports can be a long-term sustainable enterprise. Campbell has also played a major part (as chief financial underwriter) for the football team's success at Texas Tech. The fix for college sports, according to Campbell, is a change to federal law, one that would enable American universities to collectively negotiate their television contracts, something that would increase (potentially dramatically) revenue and return the money to levels where revenue sports (football, basketball) can support non-revenue sports (everything that's not football, basketball).

Universities are not waiting for government intervention to decide their options. The financial and competitive pressure has compelled action, and what has occurred so far is on a sport-by-sport basis.

College hockey [has changed noticeably](https://www.uscho.com/2025/12/24/everybody-has-a-different-path-ccha-teams-embracing-the-chl-and-the-larger-player-pool-it-gives-them) since former Canadian Hockey League (CHL) minor league junior hockey players started joining college teams. High-impact CHL freshman are producing for Maine and Penn State. In general, the deeper talent pool has more good teams and more goal-scoring.

College soccer [has moved](https://www.sportico.com/leagues/soccer/2025/ncaa-college-cup-soccer-schedule-1234878902/) in the direction of a competitive season with games during both the traditional Fall and Spring academic calendars. According to reporting by Sportico, the move syncs with MLS calendar changes and sets up lots of attention for competitive American soccer in April. The new college soccer schedule is more likely to come to NCAA Mens programs before the NCAA Womens programs.

College swimming [looks like](https://swimswam.com/is-the-college-swimming-league-the-future-kyle-sockwell-answers-the-hard-questions/) it will have a 12-team "College Swimming League" with made-for television dual meets that also count as NCAA competitions.

College basketball recently saw an NBA-drafted player, James Nnaji, gain eligibility to play for Baylor. Nnaji might join the team as soon as this January. There [may be more](https://dailyknicks.com/knicks-lose-college-unprecedented-nil-era) college basketball roster spots available for G-League players and NBA draftees looking for a place to earn a better paycheck. (The NCAA has announced rules clarifications saying that drafted basketball players are ineligible.)

***A note about college athletes and their data privacy*** Privacy is barely discussed in the conversations about new business models for college sports. As an athletes' data privacy researcher who has worked in media businesses I can see how privacy is lower priority than business and financial fundamentals. Data privacy is, however, a central aspect of athletes' basic rights. When discussions turn to asking what's best for athletes (as opposed to university or business interests) the subject of privacy emerges. In this situation privacy has become a bellwether for identifying (or ignoring) athletes' interests in discussions about the changes ahead for college sports.

### Youth Sports Burnout

A [feature-length article](https://x.com/el_belson/status/2005606439155564965) by Ken Belson looks at how and why large numbers of child athletes are failing to thrive within their youth sport experiences. Specialization, competition rank high on a long list of anxiety-inducing pressures that coaches, parents and organized youth sports in general combine to inflict on pre-teens and teens. 70 percent of child athletes drop out by age 13. Belson writes that viewing the problems in youth sports through a mental health lens is a path forward. Coping is a mechanism for kids to possibly find the fun that previous generations did not have to look so hard to find in sports.

With the 2026 Winter Olympics close to its start, a Wisconsin newspaper [asked](https://www.washingtoncountyinsider.com/5-olympic-heiden-stolz-chasing-2/) famous Olympic speed skater Eric Heiden for thoughts about the promising 21-year old U.S. speed skater Jordan Stolz. Heiden is legendary for winning short- and long-distance races, something that young skaters no longer have an opportunity to pursue. Training programs have become specialized for young skaters. Heiden feels that there is a mental advantage that comes from taking on challenges that don't materialize if it is a singular focus on winning.

Stolz made it through the gauntlet and is on the verge of his Olympic dreams. Most child athletes won't realize Olympics or professional dreams, which should be obvious. But if two-thirds of athletes don't reach higher levels of competition then the athlete development pipeline reduces dramatically. Specialization, it seems, has a lot to do with why. "Exceptional young performers reached their peak quickly but narrowly mastered only one interest (e.g., one sport). By contrast, exceptional adults reached peak performance gradually with broader, multidisciplinary practice. However, elite programs are designed to nurture younger talent," is the finding from a [review article](https://www.science.org/doi/10.1126/science.adt7790) published this week in *Science*.

Eric Cressey is Director of Player Performance for the New York Yankees and a long-time personal trainer for young baseball talents. As described in [an essay](https://x.com/EricCressey/status/2004519795757109705) from earlier this year Cressey saw a unique training window in his young daughter's rehabilitation for a broken arm. "It’s on us as coaches to a) identify where the massive growth potential exists, b) make the athlete/parents/coach aware of it, and c) close the gap with good programming and quality coaching," writes Cressey, making points that are at odds with the benefit from increased autonomy mentioned in the Belson article. These windows of "adaption," according to Cressey, "set the state for more long-term success." But if these windows come with the dependency on coaches to recognize and program then burnout should surprise no one.

### More News

* [The effects of stroboscopic vision training on physical performance in athletes: a systematic review](https://link.springer.com/article/10.1186/s13102-025-01459-x) *BMC Sports Science, Medicine and Rehabilitation* journal by Birgul Dingirdan Gultekinler et al. on Dec 19

* [Perspectives on sports analytics to inform constraint manipulation, representative learning and functional variability in practice design](https://www.sciencedirect.com/science/article/abs/pii/S0167945725001290) *Human Movement Science* journal by Ben Teune et al. on Dec 21

* [The National Science Foundation just had a big reorganization. Here are five things to know](https://www.science.org/content/article/national-science-foundation-just-had-big-reorganization-here-are-five-things-know) *Science*, ScienceInsider by Jeffrey Mervis on Dec 29

* [An App, an Apple Watch and AI: UMass Amherst Creates a New Way for Researchers to Study Sleep Health](https://www.umass.edu/news/article/app-apple-watch-and-ai-umass-amherst-creates-new-way-researchers-study-sleep-health) *News Release* University of Massachusetts Amherst on Oct 29

* [Peripheral Labs taps into self-driving car sensors to bring sports fans right into the game](https://techcrunch.com/2025/12/18/peripheral-labs-taps-into-self-driving-car-sensors-to-bring-sports-fans-right-into-the-game/) *TechCrunch* by Ivan Mehta on Dec 18