---
title: "ADCN: Public Health, Nutrition, Injury Algorithms"
author: "Brad Stenger"
date: "2025-09-08"
---

As I get the newsletter up and running it might take a few weeks to work out a regular production schedule. My goal is to have a regular once per week delivery by Thanksgiving, and then ramp up to twice per week by year end. The amount of available material is substantial, and that is exciting. Eventually, and probably soon, I should have a succinct description for what this newsletter covers and why. The voice will be technically dense, culturally relevant and fun to read. There will also be a website spinning up at <https://newsletter.bradstenger.com> as the newsletter comes together. I am using the [Quarto publishing system](https://quarto.org) and I am excited about the possibilities that the platform offers.

### Sports, Infectious Disease and Public Health Policy
*a smaller CDC puts athletes at risk*

The number of [compromised athletes from illness](https://swimswam.com/summary-of-confirmed-swimmers-with-illness-at-the-2025-world-championships/) far exceeded the number of compromised athletes from injury at the most recent Swimming World Championships in Singapore. The cause was a contagious gastroenteritis that came with U.S. swimmers from their training camp in Thailand. Elite athletes normally use 5-star facilities, and before COVID they could normally count on an environment that would not make them sick. COVID changed the rules, and no place, no matter the expense, could assure total confidence. 

[Confidence in public health](https://www.nytimes.com/2025/08/11/opinion/cdc-shooting-vaccine-misinformation.html) is about to get worse as the U.S. Centers for Disease Control (CDC) [shrinks in size and responsibility](https://theconversation.com/kennedy-hearing-deepens-crisis-over-dismantling-of-cdc-leadership-health-scholar-explains-why-the-agencys-ability-to-protect-public-health-is-compromised-264273). Leagues, teams and athletes will probably want to anticipate worst case scenarios, COVID-level precautions, in order to assure athlete health when there is regional, national or international travel for competition, whether that is for games or tournaments or Olympics or World Cups. The potential exposure combined with the high stakes for athletes' health and performance makes it almost necessary to institute bubble-like preventive measures in order to make it more likely to identify contagious infections sooner and not later. And as public health infrastructure degrades the need increases to step up bubble-type precautions. For example, personal health-monitoring measurements using wearables [has been shown](https://www.nature.com/articles/s41591-021-01593-2) to identify infections before symptoms appear.

How bad will public health get? It looks like that depends on where you go. Vermont, where I am, looks like it will establish [public health monitoring in an alliance with the other New England states](https://vtdigger.org/2025/08/28/with-cdc-in-chaos-vermont-joins-regional-coalition-to-navigate-public-health-challenges/). California, Oregon and Washington [plan something similar](https://www.opb.org/article/2025/09/03/vaccines-oregon-washington-california-cdc/) on the West coast. Properly-funded government public infrastructure has an important role in developing monitoring technologies. The wastewater monitoring that helped to corral COVID is [set to improve](https://www.opb.org/article/2025/09/03/vaccines-oregon-washington-california-cdc/) as AI and functional genomics describe real-time risk inherent to changes that occur with mutating pathogenic vectors. Eventually the tech will make it possible to where and why infectious disease risk is high. But that's not the world we have right now.

### Personalized Nutrition
*nutrition is an n=1 experiment*

More than 80% of student-athletes at the University of Georgia eat at Chipotle at least once per week. The figure is 98% for Ohio State student-athletes. The statistics are part of [the announcement](https://swimswam.com/chipotle-will-be-giving-free-meals-to-all-student-athletes-at-ohio-state-florida-and-georgia/) that Chipotle now gives student-athletes at Georgia, Ohio State and University of Florida (> 90%) coupons for free food during their sports seasons. 

There's a trend among food product developers to target demand among active populations with [new offerings](https://www.dairyfoods.com/articles/98328-sports-nutrition-manufacturers-now-target-active-lifestyle-consumers). Supplements like [creatine](https://www.npr.org/2025/09/04/nx-s1-5526053/are-creatine-supplements-all-that-theyre-pumped-up-to-be), protein and collagen have shown increased effectiveness in active populations where inactive populations do not benefit, coming from Mike Ormsbee in [his conversation](https://www.theringer.com/podcasts/the-dave-chang-show/2025/08/04/protein-with-dr-michael-ormsbee) with podcaster (and restauranteur) David Chang. The same should be true for substantial, relatively unprocessed fast casual burrito bowls. 

Ultra-endurance athletes have begun to seize [competitive advantages from fueling strategies](https://www.si.com/onsi/cycling/news/how-professional-cyclists-are-moving-the-needle-in-sports-nutrition) that make sure energy stores are not depleted. The nutrition programs have become personalized and precise. Continued progress to personalized nutrition will accelerate as the research continues. There's a good chance that future will look something like Chipotle where my order (burrito: 2x chicken, pinto beans, cheese and lettuce) is what works for me and not necessarily anyone else. The minimally processed, substantial mix of quality proteins and carbohydrates hits at the lowest common denominator of what an athlete needs but there is no single recipe that works for all athletes.

The question of how to eat becomes more important than what to eat if it becomes incumbent for each athlete to be their own personalized nutrition expert. A recent [Stanford study](https://med.stanford.edu/news/all-news/2025/06/carb-sugar-spikes.html) shows that blood sugar responses to carbohydrate intake is highly variable, and depends on individual health and metabolism. But where subtypes for general pre-diabetic populations can be measured, each and every high-performance athlete might be their own singular subtype. 

### Predicting Athletes' (Re)Injuries
*expect regular info on how algorithms and models for injury continue to evolve*

New [research out of Australia](https://www.qut.edu.au/news?id=201410) took data from one Australian Football League club to model athletes' re-injury susceptability. [The study](https://onlinelibrary.wiley.com/doi/10.1002/asmb.70034) takes athlete data for 1 season and 1 team, combining injury data for 33 athletes with performance tracking data 2500+ training and competition sessions. The injury prediction model comes from ~100 injuries, meaning that very few sessions had injuries occur, pointing to the obvious benefit from data sharing among teams in order to base results on data with more injuries and more data sets.

The work combines survival modeling and a Hidden Markov Model, an approach that tracks a range of known covariates and also incorporates hidden, unknown or unknowable factors but still provides measurable reliability for predictions. Age, it turns out, is the leading covariate factor affecting re-injury. But \"factors relating to the number of efforts exceeding 95%ile in terms of speed, perceived exertion and acceleration had significant affects on risk of re-injury.\"

The results are somewhat consistent with a 5000-person study of injured runners that [gained attention](https://run.outsideonline.com/training/injuries-and-prevention/a-single-run-could-put-you-at-risk-for-an-overuse-injury-a-new-study-suggests/) this summer. [Danish researchers](https://bjsm.bmj.com/content/59/17/1203) used Garmin data for recreational runners and identified 1820 injured athletes. Large spikes in training distances were the most frequent cause of overuse injuries which authors found to occur in 30% of runners who had at least 200 running sessions.

In both the elite athlete who is recovering from injury, or the recreational athlete who trains irregularly, it is essential to prepare for maximum effort endeavors.