---
title: "ADCN: A sports science and technology newsletter by Brad Stenger"
author: "Brad Stenger"
date: "2025-08-26"
---

Welcome to my resurrected sports science and technology newsletter. I\'ve given it a title, the \"Athletes Data Community Newsletter,\" something that reflects my research interests. 

I\'m going into my last year of a Computer Science PhD at the University of Vermont and my primary research projects focus on privacy aspects of athletes' health and performance data. Other papers in preparation: task analysis for athletes\' data technologies based on field-based research, athletes\' injury risk from an engineering systems perspective, socio-technical impediments and solutions for data sharing in sports. By putting athletes\' data front and center I think that it will be possible to discuss the varied aspects of how data gets collected, managed and applied across the full spectrum of sports. At least I hope so.

### Concussions in 2025
*flashing smart mouthguards and the growing importance of injury risk
awareness*

Football season is concussion season, according to
[CNN](https://www.cnn.com/us/nfl-concussions-fast-facts){target="_blank"}.
Fortunately research in traumatic brain injury continues to advance. A
U.S. research team led by a Milwaukee team from St. Luke\'s Medical
Center and Medical College of Wisconsin
[observed](https://journals.lww.com/acsm-msse/abstract/9900/change_in_head_impact_exposure_following.885.aspx){target="_blank"}
that 75% of football players experienced fewer head impact exposure
after return to play. Longer post-concussion recovery led to larger
decreases in head impact exposures. Conservative return-to-play
management from concussion likely increases athletes\' awareness of head
impacts and improves their ability to protect themselves. 

Awareness is
central to a smart impact-sensing mouthguard with a bright red light
that flashes above threshold acceleration values (75g for men, 65g for
women, or 4500 radians per second squared). Years ago, research
biomedical engineer [Eric
Nauman](https://scholar.google.com/citations?user=Wxcf9u8AAAAJ&hl=en){target="_blank"}
(then at Purdue, now at University of Cincinnati) told me that football
helmets should have plastic shells that would crack at similar
thresholds, and prompt the same response: Get that athlete off the
field. The evidence is the urgency, and without both, the
decision-making circumstance changes. 

An athlete, a coach or a referee
can all choose to play on without a clear and obivious signal that it is
irresponsible to continue. \"Where athletes really get themselves into
trouble -- they continue to play. They get another, even minor, hit, and
the symptoms get even more amplified,\"
[says](https://newsroom.clevelandclinic.org/2025/08/13/protecting-athletes-brains-from-concussion){target="_blank"}
Marie Schaefer of Cleveland Clinic. Technology that improves injury risk
awareness and accounting is potentially disruptive, but only if norms in
sport prioritize risk awareness. The alternative is to attribute sports
injury to bad luck and believe that athletes inevitably get hurt.

### Synthetic Data in Sports
*synthetic data is important technology for sports at the junction of
data science, data sharing and privacy*

Privacy and data sharing in sports, this is my research in the PhD program at the University of Vermont. Questions about privacy for
athletes\' health and performance data have largely been unasked, and
unanswered. So I am trying to ask them. Expect to see lots more about
these subjects in the weeks ahead.

Synthetic data, it turns out, is a crucial aspect of my research.
Synthetic data, data that is produced algorithmically as opposed to
being observed or collected, is capable of guaranteeing both privacy and
quality and lends itself to widespread sharing. Examples of
sports-related synthetic data are just proof of concept at this point. A
[study](https://www.frontiersin.org/journals/sports-and-active-living/articles/10.3389/fspor.2025.1646146/full){target="_blank"}
out of Ireland uses synthetic data to predict gait stability in an older
population. The context is more sports-adjacent than actual sports but
the work is a stepping stone to more complex biomechanical movements and
more diverse athletic populations. Earlier this summer John Warmenhoven
[derived](https://link.springer.com/article/10.1007/s40279-025-02221-6){target="_blank"}
a synthetic dataset that showed only numerical acute training load,
numerical chronic training load (4-week) and a binary injury data point,
all expressed on a per week basis. The paper is a simple how-to and
little more, \"an important first step toward better understanding of
the utility of synthetic data for the sports and exercise sciences more
broadly,\" the authors write.

### Hidden Danger of Gambling
*athletes\' performance data is essential information for sports gamblers
who seek to create a betting edge based on predictions of players\'
health, performance and injury*

A lawsuit is working its way through UK courts. A group of Premier
League players [has sued](https://uk.finance.yahoo.com/news/premier-league-players-challenge-data-213440100.html){target="_blank"} via \"stop processing\" requests in order to rein in the access that commercial operators have to player performance data. Commercial operators consist of broadcasters, game developers and gambling companies, and they have negotiated data access rights with sports leagues under collective bargaining positions that those leagues have established with its players.
Information fuels the analysis of high stakes sports gambling, and no one has higher stakes that the firms that take sports bets. Profiting from sports gambling depends on maintaining an edge that can tilt odds in ways that other bettors cannot expect. The amount of player performance data that is needed to create an edge is substantial, making it somewhat unrealistic at present. The payoff that will come from developing the edge is substantial however. 

Henry Abbott [makes the point](https://www.truehoop.com/p/incandescent-fitness){target="_blank"} in a
researched essay that team-wide health and stamina are deciding NBA
games, displacing some of the importance that star-level talent has in
teams\' game models. Longer-term, performance data has a significant
role to play in the personalized care and training that elite athletes
increasingly require, according to the Danish authors of *Consensus
Statement-Optimizing Performance of the Elite Athlete*, [recently
published](https://onlinelibrary.wiley.com/doi/10.1111/sms.70112?af=R){target="_blank"}
in the *Scandanavian Journal of Medicine & Science in Sports*. The authors
write,
> Technological innovations are likely to enable the development of
> personalized training and nutrition strategies in the next decades
> through emerging technologies. Examples include utilizing wearable
> sensors and real-time monitoring to enable precise measurement of
> individual responses in the field and utilizing multi-omics
> approaches. Combined, these innovations may allow for better tailoring
> of training and nutrition strategies across the varying demands of
> training and competition.

As the personalization advances, analysis of athletes\' data should also
provide clearer pictures for injury prevention and injury prediction.
Nothing about the future of sports scares me more than sports gamblers
inventing and then using an edge based on athlete injury prediction.