---
title: "ADCN: Women, Gene Editing, News"
author: "Brad Stenger"
date: "2026-04-25"
---

### Women Athletes' Performance Research

A Donald Trump executive order on his first day back as President in January 2025 upended the NIH Sex as a Biological Variable policy. SABV had been in place since 2015 and directed research using animal models to have both male and female models, instead of the then-common practice of just using males. The growing body of evidence that diseases and drugs affect women and men differently made NIH think it was important to start clinical research investigations off without a male-only bias. [This comes from](https://undark.org/2026/03/30/sex-biological-variable/) *Undark* magazine.

Sex differences and male-research bias are something that sports health and performance research knows well. The biannual [Female Athlete Conference](https://www.femaleathleteconference.com/) has a mission to close the disparity in research and treatment of female athletes. (Due to return in 2027.)

The institutional change in NIH research coincides with a major drop in the number of NIH grants awarded, a figure that includes substantial grant reductions for women's health, according to both *The Washington Post* ([link](https://www.reddit.com/r/NIH/comments/1st70k8/through_march_31_the_number_of_grants_awarded_by/)) and *The New York Times* ([link](https://www.threads.com/@michaeldgreenphd/post/DXca146EfC0/gift-link-to-story-f-n-agq-xkt-e-smid-nytcore-ios-share)). NIH funding is supposed to allocate $47 billion for research in fiscal 2026, but grantmaking at the institution has slowed to a crawl, according to Elizabeth Ginexi, a former NIH program official with a Substack newsletter.

And another round of massive budget cuts for U.S. science has been proposed by the Trump administration. The budget for the National Science Foundation might be reduced by 55%, from almost $9 billion to $4 billion, [according to reporting](https://www.nature.com/articles/d41586-026-01105-7) in *Nature*.

Okay, so there's a crisis in U.S. research funding. Might there be private funding available to fill in for some of the gigantic losses in public funding? The U.S. Soccer Federation [established](https://www.ussoccer.com/stories/2025/12/us-soccer-launches-kang-womens-institute-to-transform-health-performance-in-womens-game) the Kang Women's Institute in December 2025, helped by a $25 million grant from Michele Kang. The Kang Institute [announced](https://www.ussoccer.com/stories/2026/04/federation/kang-womens-institute-announces-groundbreaking-research-female-athlete-health-performance-retention) its first two initiatives, one for menstrual cycle and athlete performance research and another to investigate why young women athletes choose to stop playing competitive soccer.

These are impressive programs, but the drop in funding from NIH-scale to Kang-scale is from hundreds of millions down to millions, two orders of magnitude down.

The research work into women athletes continues. Its fundamental importance girds the continued growth in women's professional sports. Kara Swisher [interviewed](https://www.youtube.com/watch?v=93BlDxPXddY) Clara Wu Tsai, who, like Michele Kang, bridges investments into women's pro teams with research philanthropy through the Wu Tsai Human Performance Alliance.

The impressive work in women-specific sports research has produced important work, described in significant new publications.

1. [Fueling Women’s Football: Evidence‑Informed Practical Nutrition Strategies for Performance and Health](https://link.springer.com/article/10.1007/s40279-026-02413-8) in *Sports Medicine* by Abbie Smith-Ryan et al. ... This paper synthesizes current research on women’s football to develop comprehensive, evidence-informed nutritional strategies tailored to the specific demands of the sport. Four key themes are addressed: (1) energy requirements in women’s football; (2) macronutrient and nutrient-timing applications around training and match play, including an illustrative case study; (3) supporting a player with inadequate energy intake, including an illustrative case study; and (4) nutritional considerations relating to fluctuations in female sex hormones. ([free link](https://www.researchgate.net/publication/402664422_Fueling_Women's_Football_Evidence-Informed_Practical_Nutrition_Strategies_for_Performance_and_Health_Fueling_Women's_Football_Evidence-Informed_Practical_Nutrition_StrategiesA_E_Smith-Ryan_et_al))

2. [REST, Exploring Sleep Patterns and Influencing Factors in Elite Female Football Athletes](https://www.nature.com/articles/s41597-025-06331-8) ... This paper presents a novel dataset of 21 elite female football athletes comprising 17 days of actigraphy, well-being, caffeine consumption, screen time, and a daily hand strength test. This dataset aims to provide a comprehensive understanding of the interplay between lifestyle factors, sleep, and athletic performance. 

3. [Urinary Incontinence in Women Athletes: Umbrella Review and Meta-analysis of Sport-Related Factors](https://link.springer.com/article/10.1007/s40279-026-02438-z) ... Commonly used sport-label classifications showed limited explanatory value for urinary incontinence prevalence in women athletes when applied as stand-alone proxies for exposure, and may misdirect screening and prevention strategies. Within the current heterogeneous and cross-sectional evidence base, cumulative training exposure emerged as the most consistently reported correlate of urinary incontinence prevalence. These findings highlight the need for prospective studies using standardised training metrics with pelvic floor-specific measures to better characterise a multi-dimensional pelvic floor exposure.

Allison Schmitt is an American swimmer who competed in four Olympic games spanning 2008-24. Her essay in the British Journal of Sports Medicine documents her journey to achieve body literacy as an elite female athlete. What took so long? It took time for her to access, absorb, trust, and finally understand her performance data. She realized how important recovery was, even though her instinct had always been to push harder and harder to achieve her goals. "This experience taught me that athletes do not need to be ‘less tough.’ We need systems that allow toughness and intelligence to coexist," she writes. [Read this.](https://bjsm.bmj.com/content/early/2026/04/14/bjsports-2026-111873.long)

Privacy is a meaningful aspect of the research in women athletes' performance. My research (and others) shows the reluctance women athletes have when asked to share personal data. The subjects of the new studies that I listed (nutrition, sleep, pelvic floor dysfunction) are normally private. In a competitive sports context, that normally private data could matter to team success, and athletes are aware of the significance of their reluctant data contributions. So they are willing to share personal data, but the situation is suboptimal. 

Differential privacy adds noise to a dataset and, in doing so, camouflages personally identifiable information. Data analysts can work with differentially private data knowing that revealing personal information is unlikely, but they are no longer working with the pristine data that was originally collected. Hal Triedman, a differential privacy researcher at Cornell Tech, makes the point that pristine data is in nearly every case not the ground truth, since all sorts of bias and collection defects add some noise to begin with, and the loss of utility that comes with DP is overstated. 

Should researchers be using differential privacy to analyze the personal data of women athletes? Yeah, probably, but it will take some work to figure out the implementation. I would say that the privacy work is complementary to, and as important as, the research in women athletes' performance.

### Gene Editing

[An editorial comment](https://www.nature.com/articles/d41586-026-01243-y) in *Nature* by Berkeley professor Fyodor Urnov and omics technology entrepreneur Sadik Kassim says that widespread gene editing is coming soon. The authors point to personalized genetic therapies that can correct rare, disabling genetic disorders. The authors do not mention that every step towards personalized genetic clinical care is also a step towards genetic editing by athletes to improve performance -- gene doping.

There has been and probably always will be some sort of arms race between drug users and drug testers in sport. Drug testing in sports has, in many circles, been called an intelligence test, insofar as sufficient mentoring in the loopholes and countermeasures for beating drug testing is often enough to pass testing regimes and continue to compete. The trend toward incentivizing athletes and coaches who have been caught on drug tests to become informants with reduced penalties has been a controversy in athlete integrity circles.

A Medscape Europe [report](https://www.medscape.com/viewarticle/coming-age-genetic-doping-olympic-sport-2026a10004yp) on genetic doping described where things stood on the eve of the Winter Olympics in February. The report anticipates that temporary gene editing might be able to stimulate in-body production of erythropoietin (EPO), which increases red blood cell counts, leading to enhanced endurance. Plasmids are bacterial gene carriers that can reprogram cellular machinery that European researchers have targeted for future gene doping blood tests. Those tests might be the one thing that can stop sports from repeating the 1990s Tour de France.

Those tests might also be the next evolution of the never-ending arms race between drug users and drug testers.

The Australian government founded Sport Integrity Australia in 2020. The organization emphasized its education mission in order to promote athlete safeguarding from abuse in addition to its responsibility as the nation's anti-doping enforcer. SIA has been subject to [a government review](https://www.anao.gov.au/work/performance-audit/sport-integrity-australias-management-of-the-national-anti-doping-scheme), and [the report] was (https://www.aph.gov.au/Parliamentary_Business/Committees/Joint/Public_Accounts_and_Audit/AntiDopingScheme/Report_515_Inquiry_into_the_effectiveness_of_Australias_National_Anti-Doping_Scheme) just posted.  The report recommends having anti-doping tests and investigations that are consistently applied across the range of professional and Olympic sports and athletes. What began as an attempt to innovate to the benefit of national sports, in line with the Australian Institute of Sport, seems now on track to be more a bureaucratic regulator.

Looking for innovation outside the doping arms race means [talking about](https://www.insidethegames.biz/articles/enhanced-games-move-forward) the upcoming Enhanced Games, where large cash prizes will reward athletes who take performance-enhancing drugs for breaking world records in track, swimming, and weightlifting. If the primary goal of the Games is to be a media spectacle (check!), then it might also have [the secondary benefit](https://www.sciencemediacentre.co.nz/2026/04/16/will-the-enhanced-games-change-doping-in-sport-expert-qa/) of providing a few more data points that help understand cheating to enhance performance in the elite athletic context.

One way to increase the data on doping is to use privacy technology in ways that document the scope of the problem without interfering with enforcement practices. I don't think that anyone in sports is close to taking this step, which would be controversial. I am just putting the idea on the table as elite sport enters a new world of gene editing and gene doping.

### News

[Dating choices or draft picks — the cognitive science behind either is similar, CMU professors say](https://community.triblive.com/news/4023135) in *TribLive* by Kellen Stepler on April 10, 2026

[The mental toll of injury nightmares that threaten players' World Cup dreams](https://www.espn.com/soccer/story/_/id/48553612/world-cup-injuries-usmnt-sergino-dest-patrick-agyemang-stu-holden-tyler-adams) in *ESPN.com* by Jeff Carlisle on April 22, 2026

[New Aspen Institute Report on Youth Soccer Reveals “Soccer Deserts” and Rising Costs for NYC/NJ Youth](https://www.aspeninstitute.org/news/youth-soccer-nyc-nj/) in *The Aspen Institute, News* by Jon Solomon on April 21, 2026

[Why some NFL coaches think the transfer portal is killing prospect development](https://www.nytimes.com/athletic/7216707/2026/04/22/nfl-draft-transfer-portal-prospect-development/) in *The Athletic* by Bruce Feldman on April 22, 2026

[After nearly a decade away, Paul DePodesta is back in baseball. Can he help resurrect the Rockies?](https://www.nytimes.com/athletic/7212433/2026/04/21/paul-depodesta-rockies-browns-moneyball/) in *The Athletic* by Britt Ghiroli on April 21, 2026