---
title: "ADCN: Better than AI, Human Performance Computation, News"
author: "Brad Stenger"
date: "2026-04-16"
---

Next week this newsletter's sendout email will change to a new, verified mail address at bradstenger.com. Please be on the lookout. Thanks!

### Be Better

The NFL has an AI partnership with Microsoft, and [according to](https://www.espn.com/nfl/story/_/id/48446759/nfl-draft-combine-artificial-intelligence-caleb-downs-arvell-reese-david-bailey) ESPN.com's Kevin Seifert, teams are relying on that partnership and other partnerships with other technical collaborators to evaluate talent. 

At a basic level, the tools provide an objective evaluation. For physical measurables like top speed, an algorithm can pull those details from game film effectively. The computer-generated number that comes from real football is a better number than non-football speed that is on display in a 40-yard dash. As the physical measurements get more abstract, like with attempts to gauge power or change of direction, the algorithms are bound to vary. The consensus definitions for what to calculate are less universal than something like top-end speed. This makes a computer evaluation opinionated, though the opinions might not be obvious.

Users frequently benefit from computer evaluation tools by separating themselves from accountability for a decision. The classic case is how optical tracking makes line calls in tennis (and now [balls and strikes in baseball](https://dl.acm.org/doi/10.1145/3772318.3791249)). The tracking system has a margin for error. The replay animation for ball-line locations are high-level approximations and not ground truth. The machine estimates are more accurate than human referees' estimates, and that's a benefit. The larger benefit, IMO, comes from offloading the decision from a blame-able human to something that doesn't respond to blame, a computer. It keeps the game moving as much as possible, which is the real benefit.

Do NFL executives get a similar don't-blame-me benefit? Actually, no. The situation reminds me of what I see some professors doing in their classes when the answers to homeworks are lookups instead of thought exercises. What I see professors do increasingly is to structure problems where the lookup answer gets a B, and it takes a better-than-AI answer to get the A. 

Smart professors gain awareness of the AI shortcomings and target those shortcomings as learning opportunities. It requires some devoted attention to assessing the floor for what AI can do (especially as that floor rises) and some skill to pose problems that differentiate human A-grades from AI B-grades. I have also seen examples in computing education research where the AI-level response is given as the starting point for a problem, and the assignment is to develop a more substantial learned understanding from there.

NFL teams that rely too much on AI and offload their decision-making will lose to the teams that are vigilant about understanding AI shortcomings and make sure to outperform algorithmic judgements. 

The ESPN.com article spoke with Los Angeles Rams executive Les Snead, who the writers reported "can envision AI providing an impersonal -- and unbothered -- projection to compare with conventional scouting. Whereas a scout might think twice about disagreeing with the general manager, an AI application will not. He referred to the ideal use of AI as an 'assistant lieutenant' that will 'help humans be better humans.'"

Stanford University has a research group for Human-Centered Artificial Intelligence that publishes an [annual AI Report](https://hai.stanford.edu/ai-index/2026-ai-index-report). The report notes that growing percentages of younger demographics have become disillusioned with AI. They still use AI, but they don't like AI. 

The change makes sense in terms of the growing awareness of AI shortcomings. Academics have been early responders in using AI shortcomings as a resource instead of just as a source of frustration. Google [now offers](https://blog.google/products-and-platforms/products/education/ai-tools-programs-educators/) academic versions of AI products and touts the "debate feature" in NotebookLM (multiple perspectives on whatever the lookup topic happens to be) as superior interfaces for applying AI to learning.

Ethan Mollick [writes on Bluesky](https://bsky.app/profile/emollick.bsky.social/post/3mj7ybjw32c2r) that AI and education will significantly affect how we learn to write. He thinks that AI makes writing education less about logic, clarity, and argument and more about appreciating and wanting to develop a personal style.

AI writing is boring. Good writing should not be boring. (My goal for every newsletter is to make it the best thing that you'll read that day.) Style also counts in sports decision-making. Schools of thought dominate the hows and whys for teams' personnel managers and coaches. Originality, even if it is just selective mixing and matching from different schools of thought, does not receive the appreciation that it deserves. 

Fans can tell when teams rely on AI too much, as playing styles converge on what's blah, boring, and low-variance. Style is a counter to vanilla AI for sports' decision-making. Style is winning games. And style is a compelling entertainment product. 


The NFL has an AI partnership with Microsoft, and [according to](https://www.espn.com/nfl/story/_/id/48446759/nfl-draft-combine-artificial-intelligence-caleb-downs-arvell-reese-david-bailey) ESPN.com's Kevin Seifert, teams are relying on that partnership and other partnerships with other technical collaborators to evaluate talent. 

At a basic level the tools provide an objective evaluation. For physical measurables like top speed, an algorithm can pull those details from game film effectively. The computer-generated number that comes from real football is a better number than non-football speed that is on displya in a 40-yard dash. As the physical measurements get more abstract, like with attempts to gauge power or change of direction, the algorithms are bound to vary. The consensus definitions for what to calculate are less universal than something like top-end speed. This makes a computer evaluation opinionated, though the opinions might not be obvious.

Users frequently benefit from computer evaluation tools by separating themselves from accountability for a decision. The classic case is how optical tracking makes line calls in tennis (and now [balls and strikes in baseball](https://dl.acm.org/doi/10.1145/3772318.3791249)). The tracking system has a margin for error. The replay animation for ball-line locations are high-level approximations and not ground truth. The machine estimates are more accurate than human referees' estimates, and that's a benefit. The larger benefit, IMO, comes from offloading the decision from a blame-able human to something that doesn't respond to blame, a computer. It keeps the game moving as much as possible, which is the real benefit.

Do NFL executives get a similar don't-blame-me benefit? Actually, no. The situation reminds me of what I see some professors doing in their classes, when the answers to homeworks are lookups instead of thought exercises. What I see professors do increasingly is to structure problems where the lookup answer gets a B, and it takes a better-than-AI answer to get the A. 

Smart professors gain awareness of the AI shortcomings and target those shortcomings as learning opportunities. It requires some devoted attention to assessing the floor for what AI can do (especially as that floor rises) and some skill to pose problems that differentiate human A-grades from AI B-grades. I have also seen examples in computing education research where the AI-level response is given as the starting point for a problem, and the assignment is to develop a more substantial learned understanding from there.

NFL teams that rely too much on AI and offload their decision-making will lose to the teams that are vigilant about understanding AI shortcomings and make sure to outperform algorithmic judgements. 

The ESPN.com article spoke with Los Angeles Rams executive Les Snead, who the writers reported "can envision AI providing an impersonal -- and unbothered -- projection to compare with conventional scouting. Whereas a scout might think twice about disagreeing with the general manager, an AI application will not. He referred to the ideal use of AI as an 'assistant lieutenant' that will 'help humans be better humans.'"

Stanford University has a research group for Human-Centered Artificial Intelligence that publishes an [annual AI Report](https://hai.stanford.edu/ai-index/2026-ai-index-report). The report notes that growing percentages of younger demographics have become disillusioned with AI. They still use AI, but they don't like AI. 

The change makes sense in terms of the growing awareness of AI shortcomings. Academics have been early-responders for using AI shortcomings as a resource, instead of just as a source of frustration. Google [now offers](https://blog.google/products-and-platforms/products/education/ai-tools-programs-educators/) academic versions of AI products and touts the "debate feature" in NotebookLM (multiple perspectives on whatever the lookup topic happens to be) as superior interfaces for applying AI to learning.

Ethan Mollick [writes on Bluesky](https://bsky.app/profile/emollick.bsky.social/post/3mj7ybjw32c2r) that AI and education will significantly effect how we learn to write. He thinks that AI makes writing education less about logic, clarity, and argument, and more about appreciating and wanting develop a personal style.

AI writing is boring. Good writing should not be boring. (My goal for every newsletter is to make it the best thing that you'll read that day.) Style also counts in sports decision-making. Schools of thought dominate the hows and whys for teams' personnel managers and coaches. Originality, even if it is just selective mixing and matching from different schools of thought, does not receive the appreciation that it deserves. 

Fans can tell when teams rely on AI too much as playing styles converge on what's blah, boring, and low-variance. Style is a counter to vanilla AI for sports' decision-making. Style is winning games. And style is a compelling entertainment product. 

### Technical Education for Human Performance 

The highlight of my year so far has been meeting Tammy Clegg. It happened on Tuesday at a research conference in Barcelona. Dr. Clegg is a professor in the College of Information at the University of Maryland. She has written papers that make my current research into athletes' data possible (like [this one](https://onlinelibrary.wiley.com/doi/10.1002/tea.21842), and [this one](https://dl.acm.org/doi/10.1145/3313831.3376153), and [this one](https://journals.sagepub.com/doi/10.1177/20539517231179197)).

Professor Clegg has a vision for using the measurement collection and analysis of human athletic performance to teach computing and engineering fundamentals, probably at the level of a college intro course. I say "probably" because this is where I begin to hijack her vision while making no claims to speak for her. She has thought about this far more than I have. She's the expert. Not me. If you are thinking of double-hijacking what I say, go ahead, but you would be making a copy of a copy with all the quality loss that involves.

Mark Guzdial was my advisor for my Masters degree at Georgia Tech a long time ago. Guzdial was the first computing educator to use media authoring tools (images, audio, video, games) to teach computer science fundamentals. [Media computation](https://link.springer.com/chapter/10.1007/978-3-031-02216-6_4), as it came to be known, made entry-level computer science accessible and enjoyable (but not any easier). It is a crucial (and under-recognized) aspect of why undergraduate enrollments in computer science classes quadrupled between 2005-2020.

Can "human performance computation" become something analogous to media computation for entry-level instruction in relevant technical disciplines (computing, mechanical engineering, biomedical engineering, data science) that will draw the next generation of learners? It has a good chance. Media computation was possible because the authoring tools that are necessary became easy enough for almost any 19-year old to work with. With the right tools in place, developing coursework was a matter of creating a problem context that illustrated the computing fundamentals that were targeted for learning. 

Any kind of "human performance computation" course will need tools that are far easier to use than what is currently available. Once easier tools are in place, the work to connect those tools to engineering, computing, and data science lesson plans begins.

Better media authoring tools have had their own growth curve since 2005. They have evolved to a place where personal expression via TikTok and YouTube are adolescent rites of passage. Sports data technologies will become more usable. It's inevitable, and putting those technologies into an educational context where usability is essential should dramatically improve the interfaces and help the sports technologies to gain wider adoption.

Fan or athlete interest gives a young person a stake in learning the difficult material for an education in human performance computation, somewhat like how interest in media production gave students a path into learning computer science. 

As with media production, individual personal interests will be diverse. The diversity of personal interests helps to motivate and guide a learner through the material. An athlete can develop an understanding of their own physical capabilities. A wannabe coach or analyst can develop an understanding for how athleticism and tactics integrate. A fan can develop an understanding for how the human performance on display in sports makes for a compelling entertainment product. A student in a health field can develop an understanding for the benefit that comes with movement and athletic activity.

Again, the tools for understanding and implementing this learning will require a major upgrade in order to meet the needs of young learners at the start of a technical education program. It is not a question of build these better tools and they will come. The demand is there. Surfacing these tools in an education setting in addition to their use by sports performance professionals will, in the big picture, get better sports data technologies into more people's hands.

### News

[Platforms like Kalshi and Polymarket let users trade on elections, court decisions, and geopolitical events. A new opinion piece examines what that reframing of odds as probabilities, bets as trades, may mean for public health.](https://bsky.app/profile/undark.org/post/3mjfxwfqm2y2b) in *Bluesky* and *Undark* magazine on April 13, 2026

[NCAA Proposes Five-Year Eligibility Cap to Standardise Athlete Career Lengths](https://ministryofsport.com/ncaa-proposes-five-year-eligibility-cap-to-standardise-athlete-career-lengths/) in *Ministry of Sport* on April 14, 2026

[Director of Athletics Chris McIntosh to depart for inaugural role in Big Ten Conference](https://news.wisc.edu/director-of-athletics-chris-mcintosh-to-depart-for-inaugural-role-in-big-ten-conference/) in *University of Wisconsin News" by Jennifer Mnookin on April 13, 2026

[NCAA crafts new performance tech recommendations](https://www.sportsbusinessjournal.com/Articles/2026/04/06/ncaa-crafts-new-performance-tech-recommendations/) in *Sports Business Journal* by Joe Lemire on April 6, 2026

[Short-term detraining in semi-professional male football players: impact of a 5-day mid-season break on performance - an observational study](https://link.springer.com/article/10.1186/s13102-026-01654-4) in *BMC Sports Science, Medicine and Rehabilitation* by João Saldanha et al. on April 9, 2026

[The Measurement and Application of Critical Speed and D′ in Running: A Scoping Review in Sports Medicine](https://link.springer.com/article/10.1007/s40279-026-02410-x) in *Sports Medicine* journal by Mitchell Anderson et al. on April 3, 2026
