---
title: "ADCN: Journaling, Stacks vs. Open, Big Data Bowl"
author: "Brad Stenger"
date: "2025-10-29"
---

Bumps in the road to regular newsletter production. I think that there will progress toward a weekly ADCN newsletter between now and the end of the year. Once I achieve some consistency I should be able to end the "soft" launch phase that we need to work through. PhD research is, in its way, a content pipeline. The key to regular newsletter production will be wrestling the PhD content pipeline into something readable. Thanks for your patience.

### Journaling with Wearables

"Expert in yourself" is not yet a norm but among high achievers in business and sports it is headed that way. Type A personalities drive the connection between data and habits since the technology is not quite easy enough to use. Call this stuff more of a really-want-to than a need-to at this point but the utility (and probably usability too) increasing dramatically as the benefit to cost ratio increases in the near future. Read on for why the big benefits are coming, and for why personal privacy is a factor.

Habits are personal behaviors. They defy universal generalization but there is [an emerging consensus](https://knowledge.wharton.upenn.edu/podcast/this-week-in-business/what-machine-learning-reveals-about-forming-a-healthy-habit/) that gaining some habits (like gym-going) are harder and gaining other habits (like hand-washing) are easier. Self-awareness about what's healthy, productive, or both healthy and productive, might be the shortest path for someone trying to make a habit out of good habits. [Atomic Habits](https://highschool.latimes.com/opinion/review-the-power-of-tiny-wins-what-atomic-habits-taught-me-about-change/), as put forward by author James Clear, is less a personal guide to habit-formation than it is a guide to self- and environmental-awareness so that you can give yourself the best chance to succeed at habit change.

High achievers often execute on a long development arc. It is not just talent, there is also an endurance factor where sustained improvement progresses year-over-year, sometimes decade-over-decade. No short cuts. Work life incorporates personal habits and self-expertise. Overall, self-knowledge takes guesswork out of finding effective collaborators and, when there is no collaboration, self-fulfillment plugs any gaps with still more self-development productivity.

A [constraints-led approach](https://www.nytimes.com/athletic/6665943/2025/09/29/sports-training-cla-coaching-wembanyana-ohtani/) (CLA) to training is learning methodology that attempts to expedite high-level skill development by imposing constraints. The thoughtful design of the constraints comes from a coach or trainer who knows CLA and perception-action coupling, a kind of meta-cognition where sensemaking in a realistic and constrained training scenario informs future behavior. It's a higher-order habit meant to create situational preparedness in high-pressure, complex, future settings.

What if you just want to eat less bacon, or improve sleep hygiene? Garmin recently [added](https://www.dcrainmaker.com/2025/09/lifestyle-logging-journaling-health-status-vs-whoop-everything.html) a "Life Logging" feature to many of the company's recent edition sport watches. The feature matches a popular aspect of Whoop biometric-tracking bracelets. The on-screen reminders delivered to your watch attach information to a wide range of daily (the typical time interval) wellness observables. The lightweight interaction is a straightforward way to connect behavior to performance when the goal is to change both of those things. [Reporting](https://www.nytimes.com/2025/09/27/business/oura-ring-tom-hale.html) by The New York Times suggests that high-performing business executives are doing something like this with Oura rings.

Research technologies are coming that will reduce the cognitive overhead for tracking and adopting habits. [Northwestern researchers](https://news.feinberg.northwestern.edu/2025/09/19/wearable-sensors-could-reshape-obesity-treatment/) combine 2 wearables (wrist + necklace), 1 body camera, and a phone app to thoroughly document research subjects' eating habits. The system gets high-fidelity gesture data from the wearables, and the body camera also recognizes activity signatures that are unique to eating. The product of this research is an effective diagnostic, showing that overeating takes multiple forms and the patterns have emotional, behavioral and contextual dimensions. Work continues, and the hope is for clinicians to use these same tools for personalization and support to enable habit changes.

[MyFoodRepo](https://www.myfoodrepo.ai/en/blog/introducing-hei-41bb6181-237a-4acf-b94f-64d0badf6fb8) is a picture-based meal-tracking app developed by Marcel Salathe and his team at EPFL in Switzerland. The researchers combined their meal tracking with ongoing checks of microbe populations in subject microbiomes. Gut health (specifically, gut diversity), [they found](https://news.epfl.ch/news/ai-nutrition-study-finds-five-every-day-may-keep-t/), depends on how consistently a person eats well, and not just on what a person's nutrition intake is like. Habits are central to basic body function. 

Privacy protection is crucial given the personal aspects of habits. That becomes more true as the stakes elevate for good habits and personal health. Athletes are going to experience higher stakes when habits go under a microscope based on the public nature of sports performance. Understanding habit formation needs to go hand in hand with understanding how to keep that information private.

### Stacks vs. Open, Why Choose?

Hudl recently described a research meeting between the company and Mexican university researchers [on the company blog](https://www.hudl.com/blog/hudl-citec-performance-workshop-event). Hudl is among the first sports technology companies to deliver a software "stack." Software stacks go back the 2000s when most every dynamic website ran on a LAMP stack (Linux, Apache, MySql, Perl/Php/Python). The essential pieces for a sports infrastructure stack are: 1. athletes' data collection, 2. athletes' data management, 3. athletes' data analysis, and 4. athletes' data reporting. The integration of the pieces, done as seamlessly as possible, make for a stack and make that stack a more useful product than any of the singular pieces by themselves. [Teamworks](https://teamworks.com/blog/teamworks-acquires-telemetry-sports/) is the other company that makes a sports stack for teams to buy.

The risk to a team who buys a stack is lock-in, a combination of dependence on and reluctance to leave a technology platform. Lock-in, [according to](https://pluralistic.net/2024/01/24/everything-not-mandatory/) technology journalist and activist Cory Doctorow, is the first step to enshittification (platform decay) which occurs when companies with lots of dependent customers prioritize exerting control over customers, instead of delivering value to customers.

The LAMP stack was (still is) Open Source technology, which effectively steered it away from enshittification. Open Source (and the related Open Data) is a way to prioritize customer value over long term time windows. The Open Source software model demonstrated by LAMP also scaled well, supporting the explosive growth that the Internet experienced as it got its legs during the early 21st Century. Calls for Open methods and shared infrastructure and practices [like this](https://bjsm.bmj.com/content/58/6/293) by Garret Bullock and [this](https://bjsm.bmj.com/content/59/18/1270) by Natalie Kupperman promote the awareness and benefits of community stakeholding.

Research participation is different in closed and in open platforms. How? Social media data (Facebook, Twitter) used to be widely available and no-cost. Companies met the demand from researchers and developers with APIs. [Years ago I wrote](https://web.archive.org/web/20170908050806/https://www.sporttechie.com/sports-technology-problem-end-user-programming/) about how the APIs to customize sports software was not being demanded or created, and I am not sure how much progress has been made in the time since. End-user programming, as I wrote, is the bottom-up expression of demand for Open infrastructure and data. At present, Open research in sports exists, but not at scales large enough to be useful.

Top-down progress does not necessarily lead to enshittification. Bottom-up progress does not necessarily gain traction to reach broad-based utility. The need is for some optimizaton of both, top-down and bottom-up, to create a check and balance that guarantees customer value from their sports software.

### Big Data Bowl 2026

The NFL announced the criteria for its [2026 Big Data Bowl](https://operations.nfl.com/gameday/analytics/big-data-bowl/) (BDB), the annual competition where anyone can take real NFL game data and then answer important (to the NFL at least) research questions. Submissions are judged and cash prizes are given. The combination of real-world data and the accessibility of the Kaggle coding competitions platform makes BDB something far less intimidating than you might expect. There is an engaged community (that includes the NFL researchers who put forward the competition research questions and data set) and the nature of the competition is easy enough to understand and not so cutthroat. The NFL wants to gain deeper insight from the location-tracking data that wearable sensors measure for each player on the field, at a rate of 10 frames per second (in the Kaggle competition data set).

The BDB competition has one data set and two tracks. The data set is player movement tracking data for NFL passing plays leading up to the moment that the forward pass is thrown. The task, and the goal of one competition track, is to predict the ongoing player movement as the football moves through the air. The second competition track is to formulate a metric (or, short of that, a video commentary) that describes some aspect of player movement that is accessible to football professionals (like coaches) and football fans (like most Americans).

The corpus of relevant research and analysis tools did not take long to assemble:
 1. [2023 CMSAC workshop video](https://www.youtube.com/watch?v=2xg3nyPNo3s&t=2221s)
 2. [Kovalchik, Player Tracking Data in Sports](https://www.annualreviews.org/content/journals/10.1146/annurev-statistics-033021-110117)
 3. [sportyR](https://github.com/sportsdataverse/sportyR)
 4. [NFLverse](https://github.com/nflverse/nflverse)
 5. [NFLfastr](https://nflfastr.com/articles/nflfastR.html)
 6. [Get started with nflfastR](https://nflfastr.com/articles/nflfastR.html)
 7. [A Bayesian circular mixed-effects model for explaining variability in directional movement in American football](https://arxiv.org/abs/2507.06122)
 8. [NFL Ghosts: A framework for evaluating defender positioning with conditional density estimation](https://arxiv.org/abs/2406.17220)
 9. [Ron Yurko's Thoughts on Big Data Bowl 2025](https://statthinksportsanalytics.substack.com/p/thoughts-on-big-data-bowl-2025)
 10. [Survival Analysis on Progress after Caught](https://www.kaggle.com/code/lorihe/survival-analysis-on-progress-after-caught)
 11. [Modeling with Transformers](https://www.kaggle.com/code/pvabish/modeling-with-transformers-by-sumersports/notebook)
 12. [NFL Advanced Stats: How To Use Them and What They Mean](https://sumersports.com/the-zone/nfl-advanced-stats/)

The 2026 BDB competition is a step in the direction of integrating athlete biomechanics into game analysis. That's what Luke Camarao and I have in mind for our submission. If it goes well and we have useful prediction and analytics algorithms for player movement during NFL pass plays then I might also have a starting point to generate synthetic data, something where I can apply and test different amounts of noise to the contest data and then see how the added noise affects player movement predictions.