---
title: "ADCN: Team Building, Research Funding & Methods, News"
author: "Brad Stenger"
date: "2026-01-14"
---

Hope 2026 is off to a great start! This newsletter project is rounding into shape behind the scenes. I'm ready to get your feedback and incorporate any notes you have for ADCN scope and content. Just reply to this email and I should get your note directly. Thanks!

### The Science and The Art of Team Building

Kent Hughes likes his team. He's the general manager of the Montreal Canadiens, and he told a recent [media gaggle](https://montrealgazette.com/sports/hockey/hockey-inside-out/cowan-young-canadiens-have-each-others-backs-and-it-shows) that his team's recent success was "what happens when a team plays for each other." As evidence, he pointed to a [recent article](https://www.nytimes.com/athletic/6856238/2025/12/03/head-coach-star-player-clash-feedback-nba-nfl/) in *The Athletic* by Rustin Dodd, that asked "How do you hold a star athlete accountable?"

Coaches have their approaches, and results are mixed. Honest confrontational approaches fail as often as they succeed. One example cited by Dodd, a star-coach disagreement involving Memphis Grizzlies' Ja Morant and coach Tuomas Iisalo where Iisalo called out Morant in front of the team a few weeks ago. Since then Memphis' season is floundering, five games below .500. Morant looks like [he will soon be traded](https://www.si.com/nba/mannix-sources-two-trade-destinations-emerge-for-ja-morant).

The more successful approach mentioned in the article is team accountability. "The most effective mode of accountability was not handed down by a manager but instead derived from the emotional connections that employees had for each other," according to Cornell professor Diedre Snyder. (This is [her paper](https://link.springer.com/article/10.1007/s10551-021-04969-z).) "It’s teams that know each other, trust each other, have an emotional connection to each other." Leaders matters but only to create a culture where players prioritize not letting their teammates down.

Dodd has [another recent article](https://www.nytimes.com/athletic/6879941/2025/12/12/mike-vrabel-patriots-hugs-leadership/) that put coaching leadership under a microscope, specifically the leadership style of New England Patriots head coach Mike Vrabel. Vrabel is an example of a coach who pushes his players outside their comfort zones in an effort to achieve superior performance. Again, the idea is based on science. Paul Zak is a cognitive neuroscience researcher and an expert in leadership, and he feels that effective coaching requires a certain amount of bullying. 

"Our brains are so energy hungry," Zak tells Dodd. "They’re just such an enormous energy (drain) in the body that we have evolved to kind of cruise most of the time. It’s like, 'I really don’t want to expend the metabolic energy of doing something cognitively or physically difficult unless I’m really pushed to do that.' So we need to be pushed. And I’m going to celebrate it when you reach these goals."

Zak was among the first brain scientists to recognize the significance of oxytocin, a hormone that contributes to feelings of attachment, closeness and trust. Zak also [acknowledges](https://ethz.ch/en/news-and-events/eth-news/news/2025/03/an-invisible-glue.html) that the forces which compel human interaction like appearances and behaviors play critical roles alongside neurobiology. An organization can create settings for neurological bonding but lack the necessary person-to-person interaction, and vice versa. It takes the right mix of personalities throughout a coaching staff and locker room to get culture right.

When we interview student-athletes as part of my research we probe their coach-athlete interactions and we ask every question we can think of when it comes to choosing between personal development and team collaboration. What's most interesting about their answers is how their young adult thoughts come at a time when their judgements begin to form. The fact that we get thoughtful answers to these questions is, I think, indicative that the push-pull between self-development and team-contribution is an essential aspect of team sports participation. Just like every athlete differs in their physical capabilities, their mental and cognitive approach is also uniquely their own.

Are you building a team, or a collection of talent? The answer has to be both. The big difference: A collection of talent makes sense on a spreadsheet while a team makes sense in the personal interactions of everyone involved.

### Sports Research Funding, Sports Research Methods

David Spergel oversees science grantmaking at the Simons Foundation and [he spoke with a magazine editor](https://issues.org/american-science-simons-spergel-interview/) about the shifts in US science policy. Research and research funding are intimately connected. Spergel sees two possible futures for science funding in America, "One is that this proposed budget is a bump in the road and funding will stay at close to the same level. A second version is where this represents a real sea change in the relationship between government and science funding. I don’t think we know what world we’re in yet."

Universities have responded to their new reality and have cut back on new hires. Don't expect to see big new program announcements for sports research at American universities. The last two announcements that I saw come from University of Michigan and University of California-Berkeley. Michigan [launched](https://record.umich.edu/articles/u-m-asics-to-launch-groundbreaking-sport-innovation-initiative/) a $25 million research partnership with ASICS, a Japanese shoe and apparel company. Berkeley [created](https://live-cspberkeley.pantheon.berkeley.edu/womens-health-and-performance/) the Women's Health and Performance Initiative led by the school's Institute for Security and Governance with external partner SPD Sports and internal partners in Athletics, Public Health and Data Science.

The agreements give two Asian sports manufacturers access to expertise, lab facilities and athletes. I am not familiar with changing norms in Asian participatory sports but the 2032 Summer Olympics will be in Australia, giving Asian athletes a proximity advantage and increased public attention. The partnership may also signal new (or perhaps improved) recruitment pipelines to elite Asian athletes for the schools' Olympics and non-Olympics sports.

Access to athletes has become more important for sports research. The [number of research articles](https://pubmed.ncbi.nlm.nih.gov/?term=%22Athletic%20performance%2Fphysiology%22%20%5BMAJR%5D%20%22field-based%22&sort=date&page=6) in the subject area of "athletic performance" which mention "field-based" methods jumped to 46 for the years 2024 and 2025 from 10 in years 2022 and 2023. Field-based methods are studies which collect data in athletes' playing and practicing environment, and not in a laboratory (or other tightly controlled setting).

Stellingwerff et al. published [a review](https://link.springer.com/article/10.1007/s40279-025-02227-0) that is also a how-to for conducting field-based research during training camps and in competition. The authors acknowledge that they sacrifice experimental control and accuracy by taking their study outside the lab, but "development of more portable measurement equipment (e.g., indirect calorimetry, desktop blood/gas analyzers, portable laboratories, etc.) and/or wearable or consumable technologies (e.g., smart watches, sensors, core temp pills, etc.)" make field-based study more compelling.

The University of Michigan started the Athlete Innovation Initiative in the Human Performance & Sport Science Center in 2024. This program trains student researchers in new athletic data collection technologies, and connects their expertise to Michigan student-athletes and teams. Before this year of research cutbacks, there had been momentum at major US sports universities to connect relevant research labs to sports teams, including field-based investigations.

Two Michigan middle-distance track athletes, Miles Brown and Ian Hill, who both plan to go to medical school describe their experience in [a university news article](https://hpssc.umich.edu/hpssc-student-experiential-learning-initiative/). "A lot of what we were doing was looking at the different sports at the university, especially the sports that would be interested in doing some testing in this lab, and identifying what tests we could do that could be predictive of performance or injury prevention or whatever that sport would want," said Ian Hill.

With change comes uncertainty. Spergel makes the point that there is no way for philanthropy to come close to filling government's role in funding research. If the government-university research funding relationship is permanently changed, Spergel expects universities to identify and focus on strengths. That assumption fits with all of the changes to the American college sports business model where universities will have to make business decisions that will affect student-athletes.

My research funding from National Science Foundation expires at the end of the year. I hope that there is a path forward for research like mine, on privacy and athletes' data. I'm not exactly sure where to look for it. The student-athletes we talk to generally approve of sharing data for research but it always exists in the context of a player-team dynamic. There's opportunity for expanding field-based research and for connecting it to lab-based work.

**Help Me to Follow the Money** &nbsp; I'll do my best to report the announcements for sports research initiatives that occur in North America. If you hear things, please let me know. Thanks!

### News

* [Short-term - change on physical capacities of football players within few days before ACL-injury: a retrospective case-control study](https://link.springer.com/article/10.1186/s13102-025-01518-3) &nbsp; *BMC Sports Science, Medicine and Rehabilitation* by Dominik Szymski et al. on January 9, 2026

* [In the NFL, the fat lady sings the latest ... New post comparing how win probability tracks through a game](https://x.com/StatsbyLopez/status/2009375944218120350) &nbsp; *X/Twitter* by Michael Lopez on January 8, 2026

* [NWSL focuses talent spotting on Combine model](https://www.insideworldfootball.com/2026/01/07/nwsl-focuses-talent-spotting-combine-model/) &nbsp; *Inside World Football* by Nick Webster on January 7, 2026

* [Thoughts on Team Canada at World Juniors](https://x.com/HockeyThinkTank/status/2008305861366546558) &nbsp; *X/Twitter* by Topher Scott on January 5, 2026

* [FDA Loosens the Reins on Wearable Tech](https://natlawreview.com/article/fda-loosens-reins-wearable-tech) &nbsp; *National Law Review* by Blank Rome LLP on January 14, 2026

* [FDA’s New Rules for Wearables](https://www.mddionline.com/wearable-medical-devices/fda-s-new-rules-for-wearables) &nbsp; *Medical Device and Diagnostic Industry* by Claire Wallace on January 8, 2026